havivi/havivi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('login/', views.login_view, name="login"),
    path('galeria/', views.galeria_view, name="galeria"),
    path('empleo/', views.bolsa_view, name="empleo"),
    path('descargas/', views.descargas_view, name="descargas"),
    path('solicitudes/', views.solicitudes_view, name="solicitudes"),
    # path('navbar/', views.navbar_view, name="navbar"),
]

news/urls.py
from django.urls import path
from . import views

app_name='news'

urlpatterns = [
    path('noticias/', views.news_view, name="noticias"),
    path('noticias/n_detail/<new>', views.new_detail_view, name="n_detail"),
]

main/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Prueba(models.Model):
    nombre = models.CharField(max_length=145)
    descripción = models.CharField(max_length=145, null=True, blank=True)
    fecha_creacion = models.DateTimeField(
        _('Fecha de creación'), auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(
        _('Fecha de actualización'), auto_now=True)
    class Meta:
        verbose_name = "Prueba"
        verbose_name_plural = "Pruebas"

    def __str__(self):
        return self.nombre
    
class Galeria(models.Model):
    nombre = models.CharField(max_length=205)
    descripción = models.CharField(max_length=200)
    img_ubi = models.CharField(max_length=200)
    foto_bool = models.BooleanField(default=True)
    link = models.CharField(max_length=200, default="")

class Solicitudes(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=False)
    tipo = models.CharField(max_length=100)
    fecha = models.DateField(auto_now_add=True, auto_now=False)
    nombre = models.CharField(max_length=100)
    descripción = models.CharField(max_length=1000)
    objetivo = models.CharField(max_length=100)
    archivo = models.FileField(null=False)

class Empleos(models.Model):
    titulo = models.CharField(max_length=100)
    área = models.CharField(max_length=100)
    descripción = models.CharField(max_length=1000)
    requisitos = models.CharField(max_length=500)
    horario = models.CharField(max_length=100)
    paga = models.CharField(max_length=100)

class Solicitud_Empleo(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=False)
    archivo = models.FileField(null=False)
    empleo = models.ForeignKey(Empleos, on_delete=models.CASCADE)

class Descargas(models.Model):
    titulo = models.CharField(max_length=100)
    descripción = models.CharField(max_length=1000)
    formato = models.CharField(max_length=100)
    peso = models.CharField(max_length=100)
    arch_ubi = models.CharField(max_length=100)

main/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class solicitudForm(forms.Form):
    tipo_solicitud_opciones=[
        ("Proyecto","Proyecto"),
        ("Queja","Queja"),
        ("Sugeriencia","Sugeriencia")
    ]
    tipo_solicitud = forms.CharField(widget=forms.Select(choices=tipo_solicitud_opciones, attrs={
        "class" : "form-select"
    }))
    titulo_solicitud = forms.CharField()
    descripcion_solicitud = forms.CharField(widget=forms.Textarea)
    objetivo_solicitud = forms.CharField(widget=forms.Textarea)
    archivo_solicitud = forms.FileField()
    reCaptcha_solicitud = ReCaptchaField()


class solicitud_Empleo_Form(forms.Form):
    archivo_curriculum = forms.FileField()
    id_empleo = forms.CharField()
    reCaptcha_solicitud = ReCaptchaField()

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Usuario
#         fields = ['avatar']

main/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Galeria, Solicitudes, Empleos, Solicitud_Empleo, Descargas
from .forms import LoginForm, solicitudForm, solicitud_Empleo_Form

# Create your views here.

def home_view(request):
    user = request.user
    return render(request, 'home.html', {'user': user})

# def login_view(request):
#     return render(request, 'login.html')

def login_view(request):
    if request.user.is_authenticated:
        return redirect('main:home')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            usuario = authenticate(request, username=username, password=password)
            if usuario is not None:
                auth_login(request, usuario)
                if 'next' in request.GET:
                    return redirect(request.GET['next'])
                return redirect("main:home")
            else:
                error_message = "Por favor introduzca un nombre de usuario y contraseña correctos."
                messages.error(request, error_message)
    else:
        form = LoginForm()

    context = {
        'form': form,
    }
    return render(request, 'login.html', context)


def galeria_view(request):
    galeria = Galeria.objects.all()
    pagina = request.GET.get("page",1)
    try:
        paginación = Paginator(galeria, 45)
        galeria = paginación.page(pagina)
    except:
        paginación = Paginator(galeria, 45)
        galeria = paginación.page(1)
        messages.info(request,"La página que intentas buscar no existe.")
    return render(request, 'galeria.html',{
        'objeto' : galeria,
        "paginación": paginación
    })

def bolsa_view(request):
    empleos = Empleos.objects.all()
    pagina = request.GET.get("page",1)
    try:
        paginación = Paginator(empleos, 15)
        empleos = paginación.page(pagina)
    except:
        paginación = Paginator(empleos, 15)
        empleos = paginación.page(1)
        messages.info(request,"La página que intentas buscar no existe.")
    context={
        'objeto' : empleos,
        'paginación': paginación,
        'form':solicitud_Empleo_Form(),
    }
    if request.method == 'POST':
        form = solicitud_Empleo_Form(request.POST, request.FILES)
        file = request.FILES['archivo_curriculum']
        if form.is_valid():
            curriculum = Solicitud_Empleo.objects.create(
                usuario = request.user,
                archivo = file,
                empleo = Empleos.objects.get(id = form.cleaned_data['id_empleo'])
            )
            curriculum.save()
            messages.success(request, "¡Curriculum enviado con éxito para "+ empleos[int(form.cleaned_data['id_empleo'])-1].titulo +"!")
        else:
            form = solicitud_Empleo_Form()
            context={
                'objeto' : empleos,
                'paginación': paginación,
                'form':form,
            }
            messages.error(request, "La solicitud no fue enviada, completa todos los campos.")
    return render(request, 'bolsa_de_empleo.html',context)

def descargas_view(request):
    descargas = Descargas.objects.all()
    pagina = request.GET.get("page",1)
    try:
        paginación = Paginator(descargas, 30)
        descargas = paginación.page(pagina)
    except:
        paginación = Paginator(descargas, 30)
        descargas = paginación.page(1)
        messages.info(request,"La página que intentas buscar no existe.")
    return render(request, 'descargas.html',{
        'objeto' : descargas,
        'paginación': paginación,
    })

def solicitudes_view(request):
    context = {
        'form' : solicitudForm()
    }
    if request.method == 'POST':
        form = solicitudForm(request.POST, request.FILES)
        file = request.FILES['archivo_solicitud']
        if form.is_valid():
            solicitud = Solicitudes.objects.create(
                usuario = request.user,
                tipo=form.cleaned_data['tipo_solicitud'],
                nombre=form.cleaned_data['titulo_solicitud'],
                descripción=form.cleaned_data['descripcion_solicitud'],
                objetivo=form.cleaned_data['objetivo_solicitud'],
                archivo=file
            )
            solicitud.save()
            messages.success(request, "¡Solicitud enviada con exito!")
        else:
            context = {'form' : form}
            messages.error(request, "La solicitud no fue enviada, completa todos los campos.")
            return render(request, 'solicitudes.html',context)
    return render(request, 'solicitudes.html',context)

#test XD

# def navbar_view(request):
#     return render(request, 'navbar.html')

main/templates/layouts/footer.html
{% load static %}
<section class="container-fluid bg-secondary">
    <div class="row p-5">
        <div class="align-middle col mx-5 align-self-center text-center">
            <button type="button" class="btn text-center shadow bg-light m-auto" onclick="homeRed()">
                <img src="{% static 'img/nav/havivi.png' %}" class="align-self-center m-auto navbar-brand text-center" width="90px">
            </button>
            <p class="my-2 text-light">En Havivi, creemos en la fuerza de la comunidad y en la importancia de vivir cada día con plenitud.</p>
        </div>
        <div class="align-middle col mx-5 align-self-center text-center">
            <div class="row text-light">
                <h5 class="my-3 fs-3">¡Síguenos!</h5>
                <div class="col my-3">
                    <a class="link-light" target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                        </svg>
                    </a>
                </div>
                <div class="col my-3">
                    <a class="link-light" target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                        </svg>
                    </a>
                </div>
                <div class="col my-3">
                    <a class="link-light" target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-linkedin fa-10x" viewBox="0 0 16 16">
                            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <div class="align-middle col mx-5 align-self-center text-center text-light">
            <h5 class="mb-3 fs-3">¡Contactános!</h5>
            <p class="my-1">Correo@mail.com</p>
            <p class="my-1">+52 0000000000</p>
            <p class="my-1">Calle #num. Col, estado, ciudad,C.P.</p>
        </div>
    </div>
</section>

main/templates/layouts/message.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/message.css' %}" />
{% if messages %}
    <div id="message" class="shadow-lg message z-3 card text-light border-light bg-transparent my-5 mx-auto position-absolute top-0 start-50 translate-middle-x">
        {% for message in messages %}
        <div id="message_header" class="card-header border-light fs-5">{{ message }}</div>
        {% endfor %}
        <input id="cerrar-mensaje" class="btn" type="button" value="Aceptar">
    </div>
{% endif %}
<script type="text/javascript" src="{% static '/js/message.js' %}"></script>

main/templates/layouts/navBar.html
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
{% endblock %}

<nav class="navbar navbar-expand-md navbar-light bg-light px-5 z-3">
    <div class="container-fluid justify-content-center">
        <button type="button" class="btn text-center shadow bg-light" onclick="homeRed()">
            <img src="{% static 'img/nav/havivi.png' %}" class="align-self-center m-auto navbar-brand text-center" width="90px">
        </button>
        <div class="collapse navbar-collapse navBarContainer flex-grow-0 mx-auto" id="navbarSupportedContent">
            <ul class="nav text-center">
                <li class="nav-item dropdown">
                    <button type="button" class="btn">
                        <a class="text-black text-decoration-none" href="{% url 'news:noticias' %}">Noticias</a>
                    </button>
                </li>
                <li class="nav-item dropdown text-center">
                    <button type="button" class="btn">
                        <a class="text-black text-decoration-none" href="{% url 'main:galeria' %}">Galeria</a>
                    </button>
                </li>
                <li class="nav-item dropdown">
                    <button type="button" class="btn">
                        <a class="text-black text-decoration-none" href="{% url 'main:solicitudes' %}">Solicitudes</a>
                    </button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn">
                        <a class="text-black text-decoration-none" href="{% url 'main:empleo' %}">Bolsa de empleo</a>
                    </button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn">
                        <a class="text-black text-decoration-none" href="{% url 'main:descargas' %}">Descargas</a>
                    </button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn">
                        <a class="text-black text-decoration-none" target="_blank" rel="noopener noreferrer" href="https://www.paypal.com/donate/?hosted_button_id=FL5NF3SUTBQLY">Donaciones</a>
                    </button>
                </li>
            </ul>
        </div>
        {% if user.is_authenticated %}
        <div class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.is_superuser == 1 %}
                <span class="mr-2 d-none d-lg-inline text-black-600 small" style="color: black;">{{ user.username }}</span>
                {% else %}
                <span class="mr-2 d-none d-lg-inline text-black-600 small" style="color: black;">{{ user }}</span>
                {% endif %}
                {% if user.avatar %}
                <img class="img-profile rounded-circle" src="" height="35vh" width="auto">
                {% else %}
                <img class="img-profile rounded-circle" src="/media/default.png" height="35vh" width="auto">
                {% endif %}

            </a>
            <!-- Dropdown - User Information -->
            <!-- <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="">
                    <i class="fas fa-user fa-sm fa-fw mr-2 " style="color: #002052;"></i>
                    Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 " style="color: #76100f;"></i>
                    Cerrar Sesión
                </a>
            </div> -->
        </div>
        {% else %}
        <div>
            <button id="inicio-btn" class="btn" type="submit" onclick="loginRedirect()">
                <a class="text-white text-decoration-none" href="{% url 'main:login' %}">Iniciar sesión</a>
            </button>
            <button id="reg-btn" type="button" class="btn ml-1">¡Registrate!</button>
        </div>
        {% endif %}
    </div>
</nav>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script type="text/javascript">
    function homeRed(){
        document.location.href = "{% url 'main:home' %}"
    }
</script>

{% block content %}
{% endblock %}

main/templates/layouts/paginación.html
{% if paginación.num_pages > 1%}
    <div class="d-flex justify-content-center mt-4">
        <ul class="pagination">
            {% if objeto.has_previous %}
                {% if objeto.number > 2 %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="?page={{ objeto.previous_page_number }}">&lsaquo;</a></li>
            {% endif %}
            {% for page in paginación.page_range %}
                {% if forloop.last and page != objeto.number and paginación.num_pages > 7 %} 
                    {% if objeto.next_page_number != paginación.num_pages%}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objeto.number | add:1}}">...</a>
                    </li>
                    {% endif %}
                <li class="page-item">
                        <a class="page-link" href="?page={{paginación.num_pages}}">{{paginación.num_pages}}</a>
                </li>
                {% endif %}
                {% if page == objeto.number and page > 7 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page | add:-1 }}">...</a>
                </li>    
                {% endif %}
                {% if page < 7 or page == objeto.number %}
                <li class="page-item {% if page == objeto.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                </li>
                {% endif %}
            {% endfor %}
            {% if objeto.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ objeto.next_page_number }}">&rsaquo;</a>
                </li>
                {% if objeto.number < paginación.num_pages|add:"-1" %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginación.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
    {% endif %}