havivi/havivi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('login/', views.login_view, name="login"),
    path('galeria/', views.galeria_view, name="galeria"),
    path('empleo/', views.bolsa_view, name="empleo"),
    path('descargas/', views.descargas_view, name="descargas"),
    path('solicitudes/', views.solicitudes_view, name="solicitudes"),
    # path('navbar/', views.navbar_view, name="navbar"),
]

news/urls.py
from django.urls import path
from . import views

app_name='news'

urlpatterns = [
    path('noticias/', views.news_view, name="noticias"),
    path('noticias/n_detail/<new>', views.new_detail_view, name="n_detail"),
]

news/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField

import datetime

from django.contrib.auth.models import User

# Create your models here.

class Tipo_Noticia(models.Model):
    nombre_tipo = models.CharField(max_length=15)

    class Meta:
        verbose_name = "Tipo de Noticia"
        verbose_name_plural = "Tipos de Noticia"

    def __str__(self):
        return self.nombre_tipo

class Noticia(models.Model):
    titular = models.CharField(max_length=200)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    cuerpo_noticia = RichTextField(_('Cuerpo Noticia'), null=True, blank=True)
    tipo_noticia = models.ForeignKey(Tipo_Noticia, on_delete=models.CASCADE, null=True, blank=True)
    imagen_principal = models.ImageField(
        default='dummy_img.jpg', upload_to='noticias', help_text="El tamaño de la imagen deberá ser menor a 2MB", blank=True, null=True)
    fecha_creacion = models.DateTimeField(
        _('Fecha de creación'), auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(
        _('Fecha de actualización'), auto_now=True)
    
    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"

    def __str__(self):
        return self.titular

news/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import (
    Noticia,
    Tipo_Noticia,
)

# Create your views here.

def news_view(request):
    recent_news = Noticia.objects.all().order_by('-fecha_actualizacion')[0:10]

    context = {
        'recent_news': recent_news
    }

    return render(request, 'news.html', context)

def new_detail_view(request, new):
    this_new = Noticia.objects.get(pk=new)
    recent_news = Noticia.objects.all().order_by('-fecha_actualizacion')[0:10]

    context = {
        'this_new': this_new,
        'recent_news': recent_news,
    }

    return render(request, 'new_detail.html', context)

news/templates/new_detail.html
{% include 'layouts/navBar.html' %}

{% load static %}

{% load bleach_tags %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/new_detail.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Imprima&family=Inclusive+Sans:ital,wght@0,300..700;1,300..700&family=Inika:wght@400;700&family=Inria+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="main-page">
    <div class="new-container">
        <div class="new-info-container">
            <a href="" class="new-type-box {{ this_new.tipo_noticia }}">
                <h5 class="new-type">{{ this_new.tipo_noticia }}</h5>
            </a>
            <h5 class="new-date">{{ this_new.fecha_actualizacion }}</h5>
        </div>
        <h1 class="new-title">{{ this_new.titular }}</h1>
        <div class="new-img-container">
            {% if recent_news.0.imagen_principal %}
            <img src="{{ this_new.imagen_principal.url }}">
            {% else %}
            <img src="/media/dummy_img.jpg" alt="">
            {% endif %}
        </div>
        
        <div class="creator-container">
            <h5>Redactada por <a href="">{{ this_new.autor }}</a></h5>
        </div>
        
        <div class="new-body">
            {{ this_new.cuerpo_noticia|bleach }}
        </div>
    </div>
    <div class="misc-container">
        
    </div>
</div>


{% endblock %}

news/templates/news.html
{% include 'layouts/navBar.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Imprima&family=Inclusive+Sans:ital,wght@0,300..700;1,300..700&family=Inria+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="top-news-container">
    <div class="main-new top-new" onclick="redirect_detail('{{ recent_news.0.id }}')">
        <div class="tnew-text-container">
            <div class="new-info-container">
                <a href="" class="new-type-box {{recent_news.0.tipo_noticia}}">
                    <h5 class="new-type">{{ recent_news.0.tipo_noticia }}</h5>
                </a>
                <h5 class="tnew-date">{{ recent_news.0.fecha_actualizacion }}</h5>
            </div>
            <h1 class="tnew-title">{{ recent_news.0.titular }}</h1>
        </div>
        {% if recent_news.0.imagen_principal %}
        <img src="{{ recent_news.0.imagen_principal.url }}" alt="">
        {% else %}
        <img src="/media/dummy_img.jpg" alt="">
        {% endif %}
        
    </div>
    <div class="sec-news">
        <div class="sec-new top-new new2" onclick="redirect_detail('{{ recent_news.1.id }}')">
            <div class="tnew-text-container">
                <div class="new-info-container">
                    <a href="" class="new-type-box {{recent_news.1.tipo_noticia}}">
                        <h5 class="new-type">{{ recent_news.1.tipo_noticia }}</h5>
                    </a>
                    <h5 class="tnew-date">{{ recent_news.1.fecha_actualizacion }}</h5>
                </div>
                <h3 class="tnew-title">{{ recent_news.1.titular }}</h3>
            </div>
            <img src="{{ recent_news.1.imagen_principal.url }}" alt="">
        </div>
        <div class="sec-new top-new new3" onclick="redirect_detail('{{ recent_news.2.id }}')">
            <div class="tnew-text-container">
                <div class="new-info-container">
                    <a href="" class="new-type-box {{recent_news.3.tipo_noticia}}">
                        <h5 class="new-type">{{ recent_news.2.tipo_noticia }}</h5>
                    </a>
                    <h5 class="tnew-date">{{ recent_news.2.fecha_actualizacion }}</h5>
                </div>
                <h3 class="tnew-title">{{ recent_news.2.titular }}</h3>
            </div>
            <img src="{{ recent_news.2.imagen_principal.url }}" alt="">
        </div>
    </div>
</div>
<div class="news-container">
    <div class="new-row">
        {% for new in recent_news|slice:"3:" %}
        <div class="new">
            <div class="new-img-container">
                <img src="{{ new.imagen_principal.url }}">
            </div>
            <div class="new-text-container">
                <div class="new-info-container lower-news-info">
                    <a href="" class="new-type-box {{new.tipo_noticia}}">
                        <h5 class="new-type">{{ new.tipo_noticia }}</h5>
                    </a>
                    <h5 class="new-date">{{ new.fecha_actualizacion }}</h5>
                </div>
                <h3 class="new-title"><a href="{% url 'news:n_detail' new.id %}">{{ new.titular }}</a></h3>
            </div>
        </div>
        {% endfor %}
        <!-- <div class="new">
            <div class="new-img-container">
                <img src="{{ recent_news.1.imagen_principal.url }}">
            </div>
            <div class="new-text-container">
                <div class="new-info-container lower-news-info">
                    <a href="" class="new-type-box type-ambient">
                        <h5 class="new-type">{{ recent_news.1.tipo_noticia }}</h5>
                    </a>
                    <h5 class="new-date">{{ recent_news.1.fecha_actualizacion }}</h5>
                </div>
                <h3 class="new-title">{{ recent_news.1.titular }}</h3>
            </div>
        </div> -->
    </div>
</div>
{% endblock %}


<script>
    // const top_new = document.getElementsByClassName("top-new");

    // document.addEventListener("DOMContentLoaded",()=>{
    //     for (let i = 0; i < top_new.length; i++) {
    //         top_new[i].addEventListener('click',()=>{
    //             document.location.href = "{% url 'main:home' %}";
    //         })
    //     }
    // });

    function redirect_detail(url){
        document.location.href = "n_detail/" + url;
    }
</script>